version: "3"

services:
  ssgo:
   image: teddysun/shadowsocks-go
   volumes:
    - "/etc/ssgo:/etc/shadowsocks-go"
   restart: "always"
   ports:
      - "10000-10015:10000-10015"
      - "10016-10020:10016-10020/udp"
