version: "3"

services:
  ssgo:
   image: teddysun/shadowsocks-go
   volumes:
    - "/etc/ssgo:/etc/shadowsocks-go"
   restart: "always"
   ports:
      - "10000-10009:10000-10009"
      - "10000-10009:10000-10009/udp"
   dns:
      - 8.8.8.8
      - 8.8.4.4
