version: '3.1'

services:

   oneindex:
      image:setzero/oneindex
      restart: always
      ports:
      - "9080:80"
      volumes:
        - "~/oneindex/config:/var/www/html/config"
        - "~/oneindex/cache:/var/www/html/cache"
      environment:
        REFRESH_TOKEN='0 * * * *'
        REFRESH_CACHE='*/10 * * * *'
