# docker-compose.yml
version: "3"
services:
  oneindex:
    image: setzero/oneindex
    ports:
    - "88:80"
    restart: always
    environment:
    - REFRESH_TOKEN=0 * * * *
    - REFRESH_CACHE=*/10 * * * *
    # - DISABLE_CRON=true
    # - SSH_PASSWORD=root
    # - TZ=Asia/Shanghai
    volumes:
    - /root/od/config:/var/www/html/config
    - /root/od/cache:/var/www/html/cache
